PRAGMA foreign_keys = ON;

-- USUARIOS (LOGIN)
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin'
);

-- OBRAS / PROYECTOS
CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

-- TRABAJADORES
CREATE TABLE IF NOT EXISTS workers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  document TEXT,
  rate_per_day REAL NOT NULL,
  role TEXT DEFAULT 'Ayudante',
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

-- REGISTRO DE DÍAS TRABAJADOS
CREATE TABLE IF NOT EXISTS work_entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  worker_id INTEGER NOT NULL,
  project_id INTEGER NOT NULL,
  date TEXT NOT NULL,
  days_worked REAL NOT NULL DEFAULT 1,
  is_paid BOOLEAN DEFAULT 0,
  FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

-- ADELANTOS
CREATE TABLE IF NOT EXISTS advances (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  worker_id INTEGER NOT NULL,
  project_id INTEGER NOT NULL,
  date TEXT NOT NULL,
  amount REAL NOT NULL,
  is_paid BOOLEAN DEFAULT 0,
  FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

-- GASTOS INTERNOS (COMPRAS, MATERIALES, ETC)
CREATE TABLE IF NOT EXISTS expenses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL,
  date TEXT NOT NULL,
  description TEXT NOT NULL,
  amount REAL NOT NULL,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);
